name: Build Qt 6 C++ App

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Qt 6
      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'  # Specify Qt 6 version

      # 3. Install build dependencies
      - name: Install build dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y cmake build-essential wget
            wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
            chmod +x linuxdeployqt-continuous-x86_64.AppImage
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install cmake -y
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install cmake
            echo 'export PATH="/usr/local/opt/qt@6/bin:$PATH"' >> $GITHUB_ENV
          fi

      # 4. Configure CMake
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      # 5. Build the project
      - name: Build
        run: cmake --build build --config Release

      # 6. Bundle Qt libraries
      - name: Bundle Qt libraries
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            EXE=$(ls build/Release/*.exe | head -n 1)
            "$Env:Qt6Dir\bin\windeployqt.exe" "$EXE"
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            EXE=$(ls build/* | grep -v "\." | head -n 1)
            ./linuxdeployqt-continuous-x86_64.AppImage "$EXE" -appimage
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            EXE=$(ls build/* | grep -v "\." | head -n 1)
            macdeployqt "$EXE" -dmg

      # 7. Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app-${{ matrix.os }}
          path: |
            build/Release/*
            build/*.AppImage
            build/*.dmg
